### ISSUE TITLE
Achievements Scoring System

### ISSUE THREAD

**Issue by felipesanches** [agrande/lba2remake#143]
Similar to this, but with different goals:

![achievements clash royale](https://user-images.githubusercontent.com/213676/36875578-4bddf838-1d8f-11e8-9c3b-6d91e2aea264.jpeg)

Would be cool to even come up with a list here (for prototyping) of which would be cool achievements on the LBA2 game.

**Comment by agrande** [comment]
Hey, thanks for your input!
We already have an opened issue for achievements here: #134
Can you comment there and tell us a bit more about what you have in mind? Thanks!
