### ISSUE TITLE
SyntaxError: Unexpected token } (cross-env/dist/index.js:42)

### ISSUE THREAD

**Issue by felipesanches** [agrande/lba2remake#144]
![screenshot at 2018-03-03 02 09 02](https://user-images.githubusercontent.com/213676/36930821-0e4cd09e-1e88-11e8-977b-648e50a8c58c.png)

**Comment by agrande** [comment]
That's strange. Probably linux-specific, or maybe you are using an old version of node.js?
I'll try to get my hands on some linux distro and test that.

In the meantime, if you want to launch the dev-server, you can just replace `cross-env NODE_ENV=development node devserver.js` by `NODE_ENV=development node devserver.js` in _package.json_.

**Comment by felipesanches** [comment]
> maybe you are using an old version of node.js?

Now using node v0.10.40 (npm v1.4.28)

**Comment by felipesanches** [comment]
![screenshot at 2018-03-03 09 08 15](https://user-images.githubusercontent.com/213676/36934085-6e05298e-1ec2-11e8-8258-04d67f564bc2.png)

**Comment by felipesanches** [comment]
alright... v0.10 was deprecated on October 2016! :-P

I'm installng a newer version of nodejs here now. Thanks.

**Comment by agrande** [comment]
Let me know if it fixes the issue for you and I’ll add a note regarding this in the readme.

**Comment by felipesanches** [comment]
yep! It worked, it seems...
