### ISSUE TITLE
The door in the 1st scene is misplaced

### ISSUE THREAD

**Issue by felipesanches** [agrande/lba2remake#146]
![screenshot at 2018-03-03 16 28 38](https://user-images.githubusercontent.com/213676/36938483-d2bd90ee-1f00-11e8-83fa-ea016e0082eb.png)

**Comment by felipesanches** [comment]
And I can go through the door:

![screenshot at 2018-03-03 16 46 47](https://user-images.githubusercontent.com/213676/36938589-7faed6cc-1f02-11e8-98ed-5011be299e1d.png)

![screenshot at 2018-03-03 16 45 33](https://user-images.githubusercontent.com/213676/36938592-864ae354-1f02-11e8-8245-1e470e10e983.png)

**Comment by agrande** [comment]
Yeah, it's a known issue, it's due to the sprite implementation being incomplete. Basically this part is work in progress. See #67.
