### ISSUE TITLE
Tim walks without moving

### ISSUE THREAD

**Issue by felipesanches** [agrande/lba2remake#147]
![peek 03-03-2018 16-56](https://user-images.githubusercontent.com/213676/36938690-0bfdf530-1f04-11e8-851f-239be803fc6a.gif)

**Comment by agrande** [comment]
Yep. Seems like an issue with the actor script getting stuck. Probably some command not being implemented yet messing with the script expected control flow.

**Comment by xesf** [comment]
Found the issue, it was caused by an incorrect use of the wait num seconds command.
