### ISSUE TITLE
Twinsen falls "inside" a door

### ISSUE THREAD

**Issue by felipesanches** [agrande/lba2remake#148]
At the Chez Luc pub, where we talk to Tim, the waiter, I was able to fall "inside" the door. I have the impression that it happened when I walked backwards in order to exit the pub. In the animated gif below you can see Twinsen's feet walking after getting stuck "inside" the floor next to the door.

![peek 03-03-2018 16-57](https://user-images.githubusercontent.com/213676/36938719-870aa840-1f04-11e8-9397-1c3610613057.gif)

**Comment by agrande** [comment]
That's the sort of things #9 intends to fix.

**Comment by Jeffroiscool** [comment]
Some more reference of me causing this bug multiple times, also found you can walk into the stairs on the right next to the jukebox: https://i.imgur.com/mHBuPgS.gifv
