### ISSUE TITLE
Get loading image from game assets instead of having it in the repo

### ISSUE THREAD

**Issue by agrande** [agrande/lba2remake#149]
![screenshot at 2018-03-03 09 33 14](https://user-images.githubusercontent.com/213676/36934304-f173bca6-1ec5-11e8-8304-2e79ea9d511c.png)

**Comment by xesf** [comment]
The load imaged is an upscaled image using waifu2x.
Menu image has been enhaced as well and mirrored to have a wider image.

**Comment by xesf** [comment]
Same issue applies to the LBA2 ribbon added for demo purposes.
