### ISSUE TITLE
Help menu

### ISSUE THREAD

**Issue by aurelienfalco** [agrande/lba2remake#152]
Display hotkeys & keyboard configuration in the menu would be nice.
And eventually, customize the commands too.

**Comment by agrande** [comment]
Like said in Slack, why not display it as an overlay when starting the game the first time instead? I'm not sure many people check help menus...

**Comment by aurelienfalco** [comment]
I agree with the the overlay at the start of the game too.
Yet, I thought we could also make a customize menu in the "Options" menu if some commands seem to be too much an inconvenience for some users.

**Comment by agrande** [comment]
Oh yes, indeed we should have a menu for customizing key mappings. Like all games do. Including the original version of LBA2. Actually, I opened an issue for that before: #48.

**Comment by xesf** [comment]
While adding any new option item, please be aware we may not have a translation in the original HQR files.
Those will need to be included in a separate file.

**Comment by agrande** [comment]
I made a help button to show the key mappings.
Closing this for now (there's that issue for configuring key mappings: https://github.com/agrande/lba2remake/issues/48)
