### ISSUE TITLE
Opening a scene without having watched the intro movie doesn't work.

### ISSUE THREAD

**Issue by Jeffroiscool** [agrande/lba2remake#163]
Tested on the live version.
Clicking a scene to go to in the editor without having watched the intro movie you'll be stuck on the Main Menu Screen.

Example provided here: https://i.imgur.com/uBvsltG.gifv

**Comment by xesf** [comment]
Thanks for pointing that out. I missed that test when I did that integration.
I believe if you enter in editor mode with #scene number on the URL that issue won't happen.

**Comment by agrande** [comment]
Yep, doesn't happen with a scene specified in the url hash.
I'll make sure switching to another scene closes the menu.
