### ISSUE TITLE
Raceguy is stuck at point 20, talking to him makes him freeze.

### ISSUE THREAD

**Issue by Zeffuro** [agrande/lba2remake#187]
As shown in video below.

https://puu.sh/zVkz1/b101c896d9.mp4

**Comment by agrande** [comment]
Probably caused by some unimplemented script command.

**Comment by xesf** [comment]
PR was open to fix this issue.
The actor got stuck in a loop trying to reach a point. The distance checks to the point were too small not allowing the actor to actually reach it.
