### ISSUE TITLE
Feature Request: Alone in The Dark and Time Commando Support

### ISSUE THREAD

**Issue by Cool-Gamer** [agrande/lba2remake#190]
Hi Guys,

Thanks for this amazing engine remake. I look forward to playing LBA2 and LBA1 in your new engine.

In the future can you also add support for Frederick Reynal's other action adventure games: "Alone in the Dark 1 & 2 & 3" and "Time Commando"? 

There is an abandoned engine remake project for "Alone in The Dark 1-3" hosted on github. I wrote the link below in case it helps.
https://github.com/somaen/fitd-residualvm

Thanks.

**Comment by Jeffroiscool** [comment]
There seems to be a fork that's much more up to date that might help: https://github.com/byfron/fitd-residualvm

**Comment by xesf** [comment]
Time Commando have few things in common. HQR files, 3D models/animations, but I guess that's it. The rest of the engine is different.
Same for AITD. It shares some key aspects from LBA1 but the overall engine is different. 

Still, I will if we finish this one as expected we will have a good code base that can be used as a reference for those projects. It may not be us to start the project but at least be used as references.

**Comment by agrande** [comment]
Hey @Cool-Gamer, thanks for your suggestion.

Personally I'm much more interested in developing the engine towards supporting modding and new content creation. So, as @xesf said, we're not very likely to work on that anytime soon (if ever in my case).

But since this is an open-source project, I'll leave this issue opened if someone else wants to pick the subject.

**Comment by MrQuetch** [comment]
I agree with what Cool-Gamer has to say. I've actually been looking into some of the files for Time Commando using the LBA Package Editor and even a Hex Editor. I've also edited the save files for TC. I know that TC uses the same exact files for pallets and images. As far as the models are concerned, I've only found the models for the buttons, letters, and the loading watch. There are some files that no matter how I edit them, and play TC again to see what changes, nothing happens. Most of the files in the HQR also appear to be either mostly blank, or have the same string of hexadecimal values as you follow along with them. I was wondering if there is any documentation on the files at all? They would be super helpful if they exist somewhere.

**Comment by xesf** [comment]
As far as I know there is no documentation out there about the game, neither the community invested time to discover many things in the game.
Anyway, I found this blog which has some insights: http://blog.defence-force.org/index.php?page=articles&ref=ART37
