### ISSUE TITLE
Make script to convert videos and music

### ISSUE THREAD

**Issue by agrande** [agrande/lba2remake#4]
Automatically locate original game installation folder and import videos and music to *.mp4 files the first time dev server is run.

**Comment by agrande** [comment]
Commands used to convert intro video (using the english audio track among 3 tracks available):
```
ffmpeg -i VIDEO17.smk -q:v 0 -q:a 0 -filter_complex "[0:1][0:4] amerge=inputs=2" mp4\VIDEO17.avi
ffmpeg -i mp4\VIDEO17.avi -q:v 0 -q:a 0 mp4\VIDEO17.mp4
```

for the other videos:
```
ffmpeg -i VIDEO01.smk -c:v libx264 -crf 22 -pix_fmt yuv420p mp4\VIDEO01.mp4
ffmpeg -i VIDEO02.smk -c:v libx264 -crf 22 -pix_fmt yuv420p mp4\VIDEO02.mp4
ffmpeg -i VIDEO03.smk -c:v libx264 -crf 22 -pix_fmt yuv420p mp4\VIDEO03.mp4
```

SMK files need to be extracted from VIDEO.HQR

**Comment by agrande** [comment]
Possible command to use for converting music files:
`ffmpeg -i input.wav -c:a libfdk_aac -b:a 128k output.m4a`

**Comment by agrande** [comment]
NPM module with ffmpeg CLI already compiled statically for all platforms: https://www.npmjs.com/package/ffmpeg-static

This avoids contributors from having to manually install ffmpeg and make it available in their PATH.

**Comment by Jeffroiscool** [comment]
Been messing around for a good while.  
Seems like the Steam version (and possibly GOG version, haven't verified) include a LBA2.DOT file which is basically a .bin file which gets mounted into DOSbox.

Haven't been able to find a solid way of extracting the .bin file automatically. May need to be done manually with PowerISO or IZArc (7-Zip doesn't support .bin files, yeah I know. It surprised me too).

Would love to hear your thoughts on this.

**Comment by agrande** [comment]
Is it really a .bin file (like in bin / cue format), or could it be a .iso in disguise?
It sounds pretty complex. Not sure how we could deal with that automatically.
@xesf: Any idea?

**Comment by Jeffroiscool** [comment]
It really is a .bin and .cue file.

LBA2.DAT is the .cue and LBA2.DOT is de .bin file.
I've already tried browserfs to extract it (with the IsoFS parameters) but I get an API error (since it likely doesn't support .bin and .cue).
Also, like I said 7-Zip didn't enable me to look in the file whereas I have used 7-Zip countless times to check other .iso files.
I could try make a script or program in a different language but not sure if I'm going to be able to make it cross platform.
Our other options would to just give partial instructions on how to extract the .bin (PowerISO, Deamon Tools, IZArc) and continue from there.

**Comment by agrande** [comment]
Partial instructions would be a real pain for players (right now it's not a problem since we have the demo website, but at some point we may have to take it down and replace it with a standalone app).

I couldn't find any solid documentation on the bin/cue format, but surely that must exist somewhere.

**Comment by agrande** [comment]
Here is what the GOG version on Mac OS look like:

```bash
adrien:/Applications/Little Big Adventure 2.app/Contents/Resources/Little Big Adventure 2.boxer$ ls -l
total 16
drwxr-xr-x@ 68 adrien  admin   2.1K Nov 26  2013 C.harddisk/
drwxr-xr-x@  5 adrien  admin   160B Nov 26  2013 D.cdmedia/
-rwxr-xr-x@  1 adrien  admin   1.0K Nov 26  2013 DOSBox Preferences.conf*
drwxr-xr-x@  5 adrien  admin   160B Nov 26  2013 Documentation/
-rwxr-xr-x@  1 adrien  admin   1.4K Nov 26  2013 Game Info.plist*
```

The C.harddisk folder contains the HQR, OBL and ILE files accessible without requiring decompression. But the VOX files can't be found there, even after playing the game, which would supposedly copy the voice files.

In the D.cdmedia folder I seem to also have a bin / cue image of the original CDrom.

```bash
adrien:/Applications/Little Big Adventure 2.app/Contents/Resources/Little Big Adventure 2.boxer$ ls -l D.cdmedia/
total 1368832
-rwxr-xr-x@ 1 adrien  admin   665M Nov 26  2013 LBA2.GOG*
-rwxr-xr-x@ 1 adrien  admin   3.8M Nov 26  2013 LBA2.OGG*
-rwxr-xr-x@ 1 adrien  admin   134B Nov 26  2013 tracks.cue*
```

Does that cue file look similar to the one you have?

```bash
adrien:/Applications/Little Big Adventure 2.app/Contents/Resources/Little Big Adventure 2.boxer$ cat D.cdmedia/tracks.cue 
FILE "LBA2.GOG" BINARY
  TRACK 01 MODE1/2352
    INDEX 01 00:00:00
FILE "LBA2.OGG" MP3
  TRACK 02 AUDIO
      INDEX 01 00:00:00
```

**Comment by agrande** [comment]
Seems like cue / bin are raw disk images. I suppose it wouldn't be too hard to just open the file and parse it manually. I'll try to dig in the format a bit further.

**Comment by Jeffroiscool** [comment]
Yeah they are the same. It's just that the GOG version has it renamed to .GOG (I got both versions).
It's all the same.
OGG fine isn't as interesting since it's just 1 track.

**Comment by agrande** [comment]
https://github.com/joncampbell123/dosbox-x/blob/master/src/dos/cdrom_image.cpp

**Comment by pleasenophp** [comment]
I managed to unpack the LBA2.GOG file. It's not hard - just run the dosbox and mount the folder containing LBA2.GOG e.g. to C: drive.
mount C "/Users/foo/myPathToFolderWithLBA2Files"

After that mount the image to D drive
c:
imgmount d "LBA2.GOG" -t iso
d:
dir

Then you will see all the files. You need the whole LBA2 folder. To copy it recursively to C: drive where your folder is mounted you need to use some tool or script, as MS-DOS copy doesn't support recursive copy of the folders. I have used Volkov Commander from dosbox. You can grab it from here: https://archive.org/details/TheVolkovCommander_1020

So now this LBA2 folder is ready to be placed as www/data 

However, there are many issues as e.g. VOX files are not in compatible name and format. All my VOX files were named FR_000.VOX etc, while game expects FR_000_AAC.VOX, etc.

Just renaming them doesn't help - the script doesn't reconize the format, so I had to download original files from the demo web resources. The same will happen with SAMPLES_AAC.HQR that in DOS version are just SAMPLES.HQR.

After that, and after downloading some mp4 files, the game started to work for me. 

So yes, you can mostly use DOS version from GoG, but there will be some issues with some of the files. The engine is not ready to support the DOS version of LBA 2 yet, and that can be an issue for people like me that own GoG version. Maybe a separate issue should be created for this.
